INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'The Witcher', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Venom: Tempo de Carnificina', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vIgyYkXkg6NC2whRbYjBD7eb3Er.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Espetacular Homem-Aranha 2: A Ameaça de Electro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/u7SeO6Y42P7VCTWLhpnL96cyOqd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Matrix Resurrections', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hv7o3VgfsairBoQFAawgaQ4cR1m.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shang-Chi e a Lenda dos Dez Anéis', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cinER0ESG0eJ49kXlExM0MEWGxW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Django Livre', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Titanic', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yDI6D5ZQh67YU4r2ms8qcSbAviZ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Lobo de Wall Street', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aves de Rapina: Arlequina e sua Emancipação Fantabulosa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jiqD14fg7UTZOT6qgvzTmfRYpWI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Rogue One: Uma História Star Wars', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6t8ES1d12OzWyCGxBeDYLHoaDrT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: A Guerra dos Clones', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uK15I3sGd8AudO9z6J6vi0HH1UU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: Episódio I - A Ameaça Fantasma', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/36LnijfQCOC89rCMOhn2OINXROI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Ultimato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cisne Negro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqh5O4KssfJWI62HGAgrjHXbxhD.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Silêncio dos Inocentes', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Clube da Luta', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hZkgoQYus5vegHoetLkCJzb17zJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guerra Mundial Z', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/31VpBgUX5O4Z3dn5ZbX8HLqoXH3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e as Relíquias da Morte - Parte 1', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vcrgU0KaNj5mKUCIQSUdiQwTE9y.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e a Pedra Filosofal', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lvOLivVeX3DVVcwfVkxKf0R22D8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Alice no País das Maravilhas', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qNdlZgz9yoSJ8f0YxQWfKGPoVV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Animais Fantásticos e Onde Habitam', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8Qsr8pvDL3s1jNZQ4HK1d1Xlvnh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Teoria de Tudo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kq2MHrRfH6RTfkvyDEmYLmGHE6U.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Livro de Boba Fett', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Último Duelo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4LrL40XecjGLRpX5I2gzMTUt04l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Interestelar', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Contato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Duna', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aquaman', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2cUsDz4TzFYHrKktT1bKHHQ7Cgm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Doutor Estranho no Multiverso da Loucura', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Projeto Adam', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Batman', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/xHrp2pq73oi9D64xigPjWW1wcz1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Uncharted', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Moonfall: Ameaça Lunar', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9Ngw106BLlNJ4iVpRHlrDfaLpCV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os Caras Malvados', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fEe5fe82qHzjO4yej0o79etqsWV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha: Sem Volta Para Casa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sonic 2: O Filme', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cidade Perdida', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Morbius', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/gG9fTyDL03fiKnOpf2tr01sncnt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Encantado', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2hZd9enh7Fhyrw8Fw08T7EDtin9.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Red: Crescer é Uma Fera', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Animais Fantásticos: Os Segredos de Dumbledore', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, '365 Dias: Hoje', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/t9hNIUFcy0tYu55IPxjxRTTdZ6X.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Hotel Transilvânia: Transformonstrão', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qBLEWvJNVsehJkEJqIigPsWyBse.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Agente das Sombras', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iDeWAGnmloZ5Oz3bocDp4rSbUXd.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Era do Gelo: As Aventuras de Buck', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eG0oOQVsniPAuecPzDD1B1gnYWy.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Exorcismo Sagrado', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jCDycDqFJ1dIv5iJfTfub2h4ZAB.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Sing 2', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6mJrgL7Mi13XjJeGYJFlD6UEVQw.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);
